
```{r}
library(boot)
library(ggplot2)
```


```{r}

inizio<-"2020-10-01T00:00:00"
end<-"2021-02-16T00:00:00"
df_sub_ext <- df_sub_ext[df_sub_ext$data >= inizio & df_sub_ext$data <=end,]

 #GAM POISSON
formula_gam_poisson = totale_ospedalizzati ~ s(mean_nuovi_positivi) + s(mean_dimessi_guariti_per_day) +I(rt^2)
gam_poisson <- gam(formula_gam_poisson , data=df_sub, family = poisson(link = log),method="REML")
gam_poisson_pred<-predict(gam_poisson, newdata = df_sub_ext, type = "response", se.fit=T)

#GAM GAMMA
formula_gam_gamma = totale_ospedalizzati ~ s(mean_nuovi_positivi) + s(mean_dimessi_guariti_per_day) +I(rt^2)
gam_gamma <- gam(formula_gam_gamma , data=df_sub, family = Gamma(link = log),method="REML") 
gam_gamma_pred<-predict(gam_gamma, newdata = df_sub_ext, type = "response", se.fit=T)

#GLM GAMMA
formula_glm_gamma = totale_ospedalizzati ~ mean_nuovi_positivi + log(mean_dimessi_guariti_per_day)*I(rt^2) + rt
glm_gamma <- glm(formula_glm_gamma, data=df_sub, family = Gamma(link = "log")) 
glm_gamma_pred<-predict(glm_gamma, newdata = df_sub_ext, type = "response", se.fit=T)

#GLM quasi poisson
formula_glm_qspoisson = totale_ospedalizzati ~ mean_nuovi_positivi+ sqrt(mean_dimessi_guariti_per_day)*I(rt^2) + rt
glm_qspoiosson<- glm(formula_glm_qspoisson, data=df_sub, quasipoisson)
glm_qspoiosson_pred<-predict(glm_qspoiosson, newdata = df_sub_ext, type = "response", se.fit=T)

#GLM quasi poisson dummy
formula_glm_qspoisson_dummy = totale_ospedalizzati ~ mean_nuovi_positivi+ sqrt(mean_dimessi_guariti_per_day)*dummy + rt
glm_qspoisson_dummy <- glm(formula_glm_qspoisson_dummy, data=df_sub, quasipoisson)
glm_qspoisson_dummy_pred<-predict(glm_qspoisson_dummy, newdata = df_sub_ext, type = "response", se.fit=T)

#GLM gamma dummy
formula_glm_gamma_dummy = totale_ospedalizzati ~ mean_nuovi_positivi + log(mean_dimessi_guariti_per_day)*dummy + rt
glm_gamma_dummy <- glm(formula_glm_gamma_dummy, data=df_sub, family = Gamma(link = "log"))
glm_gamma_dummy_pred<-predict(glm_gamma_dummy, newdata = df_sub_ext, type = "response", se.fit=T)
```



```{r, echo=FALSE}

boot_fun <- function(data, indices, formula) {
    d_train=data[indices,]
    
     model = gam(formula_gam_poisson , data=d_train, family = poisson(link = log),method="REML") #GAM POISSON
    # model = gam(formula_gam_gamma , data=d_train, family = Gamma(link = log),method="REML") #GAM GAMMA
    # model = glm(formula_glm_gamma, data=d_train, family = Gamma(link = "log")) #GLM GAMMA
    # model = glm(formula_glm_qspoisson, data=d_train, quasipoisson) #GLM qusi poisson
    # model = glm(formula_glm_qspoisson_dummy, data=d_train, quasipoisson) #GLM quasi poisson DUMMY
    # model = glm(formula_glm_gamma_dummy, data=d_train, family = Gamma(link = "log"))
  
    pred <- predict(model, df_sub_ext, se.fit=FALSE, type="response")
  
  return (pred) 
}


 b <- boot(data = df_sub, statistic = boot_fun, formula = formula_gam_poisson,  R=5000, ncpus=4, parallel="multicore")
# b <- boot(data = df_sub, statistic = boot_fun, formula = formula_gam_gamma,  R=5000, ncpus=12, parallel="multicore")
# b <- boot(data = df_sub, statistic = boot_fun, formula = formula_glm_gamma,  R=5000, ncpus=12, parallel="multicore")
# b <- boot(data = df_sub, statistic = boot_fun, formula = formula_glm_qspoisson,  R=5000, ncpus=12, parallel="multicore")
# b <- boot(data = df_sub, statistic = boot_fun, formula = formula_glm_qspoisson_dummy,  R=5000, ncpus=12, parallel="multicore")
# b <- boot(data = df_sub, statistic = boot_fun, formula = formula_glm_gamma_dummy,  R=5000, ncpus=12, parallel="multicore")

# library(broom)
# tidy(qp.glm2_avg.rt) #to see summary


ci <- do.call(rbind, lapply(1:nrow(df_sub_ext), function(i) {
  boot.ci(b,type="perc",conf=.95,index=i)$percent
}))

df_grafico <- df_sub_ext

 df_grafico$predict<-as.numeric(gam_poisson_pred$fit)
# df_grafico$predict<-as.numeric(gam_gamma_pred$fit)
# df_grafico$predict<-as.numeric(glm_gamma_pred$fit)
# df_grafico$predict<-as.numeric(glm_qspoiosson_pred$fit)
# df_grafico$predict<-as.numeric(glm_qspoisson_dummy_pred$fit)
# df_grafico$predict<-as.numeric(glm_gamma_dummy_pred$fit)

df_grafico$lower <- ci[, 4]
df_grafico$upper <- ci[, 5]

 png("GAM_Poisson.png", units="in", width=8, height=4, res=300)
# png("GAM_Gamma.png", units="in", width=8, height=4, res=300)
# png("GLM_Gamma.png", units="in", width=8, height=4, res=300)
# png("GLM_Quasi.png", units="in", width=8, height=4, res=300)
# png("GLM_Quasi_dummy.png", units="in", width=8, height=4, res=300)
# png("GLM_Gamma_dummy.png", units="in", width=8, height=4, res=300)

ggplot(df_grafico, aes(x=as.Date(data), y=totale_ospedalizzati) ) +
    geom_point(size = 1,shape=18, aes(col='Real data')) +
    geom_ribbon(aes(ymin = lower, ymax = upper), fill = "black",
                alpha=0.5) +
    xlab("Date") +
    ylab("Totale ospedalizzati") +
    
     labs(title="GAM Poisson model") +
    # labs(title="GAM Gamma model") +
    # labs(title="GLM Gamma model") +
    # labs(title="GLM Quasi-Poisson model") +
    # labs(title="GLM Quasi-Poisson with dummy model") +
    # labs(title="GLM Gamma with dummy model") +
    
    scale_y_continuous(breaks = seq(0,18000,by=2000)) + 
    geom_line(aes(x=as.Date(data), y=predict, col="Model"), size=1) +
    geom_vline(xintercept=as.numeric(df_grafico$data[124]), linetype=4) +
    scale_color_manual(name="", values=c("#db3236","#3cba54")) +
    theme(
      plot.title = element_text(size = 15, face = "bold",hjust = 0.5),
      axis.title = element_text(face = "bold"), 
      axis.text = element_text(color= "#2f3030", face="bold"),
      legend.key.size = unit(1, "cm"),
      text = element_text(size=12)
      )

dev.off()
```



